spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/interview-exercise
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  liquibase:
    drop-first: false
